version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://ass-doordash-lambda-deployment-code-bucket/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name doordash-lambda --s3-bucket ass-doordash-lambda-deployment-code-bucket --s3-key deployment_package.zip
      - echo "Deployment complete!"